local function scrape()
    nat_metric = metric("switch_mib", "gauge")
    local function get_reg_value(addr)
        local handle = io.popen("switch reg read " .. addr, "r")
        if not handle then return 0 end
        local line = handle:read("*a")
        handle:close()
        local val = string.match(line, "value=(%x+)")
        return  val and tonumber(val, 16) or 0
    end
    local function word2doubleword(high,low)
        return high * (2^32) + low
    end
    local low32 = get_reg_value("0x4048")
    local high32 = get_reg_value("0x404c")
    local data =word2doubleword(high32,low32)
    nat_metric({port=0,flow='tx',type='Octet'}, data)
    low32 = get_reg_value("0x40A8")
    high32 = get_reg_value("0x40Ac")
    data =word2doubleword(high32,low32)
    nat_metric({port=0,flow='rx',type='Octet'}, data)
    low32 = get_reg_value("0x4148")
    high32 = get_reg_value("0x414c")
    data =word2doubleword(high32,low32)
    nat_metric({port=1,flow='tx',type='Octet'}, data)
    low32 = get_reg_value("0x41A8") 
    high32 = get_reg_value("0x41Ac")
    data =word2doubleword(high32,low32)
    nat_metric({port=1,flow='rx',type='Octet'}, data)
    low32 = get_reg_value("0x4248")
    high32 = get_reg_value("0x424c")
    data =word2doubleword(high32,low32)
    nat_metric({port=2,flow='tx',type='Octet'}, data)
    low32 = get_reg_value("0x42A8") 
    high32 = get_reg_value("0x42Ac")
    data =word2doubleword(high32,low32)
    nat_metric({port=2,flow='rx',type='Octet'}, data)
    low32 = get_reg_value("0x4348")
    high32 = get_reg_value("0x434c")
    data =word2doubleword(high32,low32)
    nat_metric({port=3,flow='tx',type='Octet'}, data)
    low32 = get_reg_value("0x43A8")
    high32 = get_reg_value("0x43Ac")
    data =word2doubleword(high32,low32)
    nat_metric({port=3,flow='rx',type='Octet'}, data)
    low32 = get_reg_value("0x4448")
    high32 = get_reg_value("0x444c")
    data =word2doubleword(high32,low32)
    nat_metric({port=4,flow='tx',type='Octet'}, data)
    low32 = get_reg_value("0x44A8")
    high32 = get_reg_value("0x44Ac")
    data =word2doubleword(high32,low32)
    nat_metric({port=4,flow='rx',type='Octet'}, data)
    low32 = get_reg_value("0x4548")
    high32 = get_reg_value("0x454c")
    data =word2doubleword(high32,low32)
    nat_metric({port=5,flow='tx',type='Octet'}, data)
    low32 = get_reg_value("0x45A8")
    high32 = get_reg_value("0x45Ac")
    data =word2doubleword(high32,low32)
    nat_metric({port=5,flow='rx',type='Octet'}, data)
    low32 = get_reg_value("0x4648")
    high32 = get_reg_value("0x464c")
    data =word2doubleword(high32,low32)
    nat_metric({port=6,flow='tx',type='Octet'}, data)
    low32 = get_reg_value("0x46A8")
    high32 = get_reg_value("0x46Ac")
    data =word2doubleword(high32,low32)
    nat_metric({port=6,flow='rx',type='Octet'}, data)

end

return { scrape = scrape }

